apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      containers:
      - name: auction-svc
        image: dietbrand/auction-svc
        env:
          - name: RabbitMq__Host
            value: rabbitmq-clusterip
          - name: RabbitMq__Username
            value: rabbit
          - name: RabbitMq__Password
            value: rabbitpw
          - name: ConnectionStrings__DefaultConnection
            value: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
          - name: IdentityServiceUrl
            value: https://id.haven2.net
          - name: Kestrel__Endpoints__Grpc__Protocols
            value: http2
          - name: Kestrel__Endpoints__Grpc__Url
            value: http://+:7777
          - name: Kestrel__Endpoints__WebApi__Protocols
            value: http1
          - name: Kestrel__Endpoints__WebApi__Url
            value: http://+:80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  selector:
    app: auction-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc
