apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: dietbrand/bid-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: RabbitMq__Host
            value: rabbitmq-clusterip
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
          - name: ConnectionStrings__BidDbConnection
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: connString
          - name: IdentityServiceUrl
            value: https://id.haven2.net
          - name: GrpcAuction
            value: http://auction-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 8080
