apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
spec:
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      labels:
        app: search-svc
    spec:
      containers:
      - name: search-svc
        image: dietbrand/search-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: RabbitMq__Host
            value: rabbitmq-clusterip
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
          - name: ConnectionStrings__MongoDbConnection
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: connString
          - name: AuctionServiceUrl
            value: http://auction-clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  selector:
    app: search-svc
  ports:
  - port: 80
    targetPort: 8080
