apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: dietbrand/auctional-webapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: authSecret
          - name: NEXTAUTH_URL
            value: https://app.haven2.net
          - name: API_URL
            value: http://gateway-clusterip/
          - name: ID_URL
            value: https://id.haven2.net
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000

