name: Build and push Bid Service image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'src/BiddingService/**'

env:
  REGISTRY_IMAGE: dietbrand/did-svc
  DOCKERFILE: src/BiddingService/Dockerfile
  DEPLOYMENT_NAME: bid-svc

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      # TODO: Set up tunnel between k8s and digital ocean droplet
      # - name: Rollout and restart deployment
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.PKEY }}
      #     script: ~/.local/bin/kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
