name: Deploy Identity Server

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'src/IdentityService/**'

env:
  REGISTRY_IMAGE: dietbrand/identity-svc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/IdentityService/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
      - name: Update identity server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PKEY }}
          script: cd ~/auctional && docker pull ${{ env.REGISTRY_IMAGE }} && docker compose up -d
